on:
  workflow_dispatch:
  push:
    branches:
      - '**'

concurrency:
  group: ${{github.repository}}-${{github.ref_name}}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - name: Retrieve required files
      run: wget -q --show-progress "https://myrient.erista.me/files/No-Intro/Nintendo%20-%20Nintendo%2064%20%28BigEndian%29/Super%20Mario%2064%20%28Japan%29.zip" && unzip "Super Mario 64 (Japan).zip" && mv "Super Mario 64 (Japan).z64" baserom.jp.z64

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag sm64

    - name: Run the Docker image
      run: docker run --rm --mount type=bind,source="$(pwd)",destination=/sm64 sm64 bash makecontinuous.sh ${{github.event.repository.name}} ${{github.ref_name}}

    - name: Push build to GitHub releases
      uses: docker://ghcr.io/mini-bomba/create-github-release:v1.2.0
      with:
        token: ${{secrets.GITHUB_TOKEN}}
        name: "Continuous Pre-releases"
        tag: "continuous"
        body: |
            This automatic pre-release is built from commit ${{github.sha}} and was triggered by @${{github.actor}}
            [Github Actions workflow run that built this pre-release](https://github.com/${{github.repository}}/actions/runs/${{github.run_id}})
            
            Builds from other branches are also available under this pre-release. The latest build is `${{github.event.repository.name}}-${{github.ref_name}}.bps`.
            
            Please note that there may be breaking changes in these builds, and that they aren't recommanded for regular play sessions.
            
            Commit message from latest build:
            ${{github.event.head_commit.message}}
        files: ${{github.event.repository.name}}-${{github.ref_name}}.bps
        clear_attachments: false
        prerelease: true